
spring.datasource.url=jdbc:mysql://localhost:3306/saxnart?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=12345

#spring.datasource.url=jdbc:mysql://103.138.88.44:3306/sax03147_localhost?createDatabaseIfNotExist=true&useSSL=true
#spring.datasource.username=sax03147_root
#spring.datasource.password=JwOZBGv;O-%e


spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect

#spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.hibernate.ddl-auto= update

spring.main.allow-circular-references=true